env:
  browser: true
  commonjs: true
  es6: true
extends: [
  'eslint:recommended', 
  'prettier', 
  'plugin:prettier/recommended'
  ]
plugins: [
    'prettier'
  ]
globals:
  __dirname: writable
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: { 
  'prettier/prettier': 'error'
}

